### ISSUE TITLE
Code rendered incorrectly

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-ai#45]
See below. Is there a bug perhaps in how we detect and format code blocks? It could very well be that ChatGPT gave us a garbage response, but I've never seen this before, including from ChatGPT itself.

<img width="861" alt="image" src="https://github.com/pulumi/pulumi-ai/assets/3953235/d0d6bfbe-6559-48af-b9d3-8416253a7afb">

**Comment by lukehoban** [comment]
We've seen a few cases where tokens appear to be dropped between the Pulumi AI backend and front end.  It's possible these are cases where the OpenAI API returns multiple tokens per "chunk" in its streaming results.  It does seem like it's become more common recently, perhaps due to performance improvements from the GPT4 API that may be triggering some race condition in our streaming implementation?

**Comment by joeduffy** [comment]
I just saw what I think is this again in a weird way; notice the "Google Cloud PlatformG)" bit:

```
The pattern you're asking about describes setting up a VPC (Virtual Private Cloud) within Google Cloud PlatformG), creating subnetworks within that VPC, and applying firewall rules to control the traffic within and between these subnetworks.
```

@AaronFriel Am I correct that the imminent release (today) will address this problem?

**Comment by AaronFriel** [comment]
Yeah, that looks like it dropped tokens around (GCP).

**Comment by AaronFriel** [comment]
It looks like this was addressed with the new site rollout; seen no reports since.
